name: Build and deploy Python project to Azure Function App - marlu-timesheet-rates

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into package folder
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Zip package
        run: |
          zip -r release.zip . \
            --exclude "*.git*" \
            --exclude "*__pycache__*" \
            --exclude "*.xlsx" \
            --exclude "*.parquet" \
            --exclude "venv/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ADB18A56A1A147B2900B2233AB6C773A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ED01B44A51BB4A669C191CECF31EF87C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_37E9D4671EC94C95827A868BFD341AB1 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'marlu-timesheet-rates'
          slot-name: 'Production'
          package: release.zip
